package festivalcine;

public enum TipoPremio {
	BIZNAGA_MALAGA_CINEMA_MEJOR_ACTRIZ, MEJOR_INTERPRETACION_MASCULINA,
	BIZNAGA_ORO_MEJOR_PELICULA_ESPANOLA, PREMIO_DEL_PUBLICO, MEJOR_GUION,
	MEJOR_INTERPRETACION_FEMENINA, MEJOR_DIRECCION,  MEJOR_INTERPRETACION_FEMENINA_REPARTO,
	BIZNAGA_ORO_MEJOR_PELICULA_IBEROAMERICANA, MEJOR_MUSICA, MEJOR_FOTOGRAFIA,
	MEJOR_INTERPRETACION_MASCULINA_REPARTO, MEJOR_MONTAJE, PREMIO_ESPECIAL_DEL_JURADO,
	PREMIO_ESPECIAL_DEL_JURADO_CRITICA

}
